import { useI18n } from 'vue-i18n'

const russianLiterals: Record<string, string> = {
  'Loading...': 'Загрузка...',
  'Saving...': 'Сохранение...',
  'Creating...': 'Создание...',
  'Removing...': 'Удаление...',
  'Clear': 'Очистить',
  'Cancel': 'Отмена',
  'Submit': 'Отправить',
  'Follow': 'Подписаться',
  'Following': 'Вы подписаны',
  'Your library': 'Ваша библиотека',
  'Your playlists': 'Ваши плейлисты',
  'Back': 'Назад',
  'Forward': 'Вперёд',
  'Open': 'Открыть',
  'Close': 'Закрыть',
  'Expand sidebar': 'Развернуть боковую панель',
  'Collapse sidebar': 'Свернуть боковую панель',
  'Editor': 'Редактор',
  'Current image': 'Текущее изображение',
  'Current cover': 'Текущая обложка',
  'Current track': 'Текущий трек',
  'Listener': 'Слушатель',
  'user': 'пользователь',
  'profile': 'профиль',
  'edited': 'изменено',
  'empty': 'пока пусто',
  'track': 'трек',
  'tracks': 'треков',
  'follower': 'подписчик',
  'followers': 'подписчиков',
  'Your Library': 'Ваша библиотека',
  'Discover new genre': 'Открыть новый жанр',
  'Discover a new genre': 'Откройте для себя новый жанр',
  'Building recommendations...': 'Подбираем рекомендации...',
  'Choose a genre first': 'Сначала выберите жанр',
  'Open Discover new genre from the sidebar and pick a genre to build recommendations.': 'Откройте раздел выбора жанра в боковой панели и выберите жанр, чтобы получить рекомендации.',
  'No recommendations available for “{genre}”.': 'Для жанра «{genre}» рекомендации не найдены.',
  '5 recommendations for {genre}, based on your liked songs': '5 рекомендаций для жанра {genre} на основе ваших любимых треков',
  'Pick a genre from the sidebar flow to see recommended tracks': 'Выберите жанр через боковую панель, чтобы увидеть рекомендованные треки',
  'What do you want to play?': 'Хотите что-то найти?',
  'Searching...': 'Поиск...',
  'Nothing found': 'Ничего не найдено',
  'Tracks': 'Треки',
  'Albums': 'Альбомы',
  'Playlists': 'Плейлисты',
  'Artists': 'Исполнители',
  'Users': 'Пользователи',
  'Genres': 'Жанры',
  'Genre': 'Жанр',
  'Artist': 'Исполнитель',
  'Album': 'Альбом',
  'Playlist': 'Плейлист',
  'User': 'Пользователь',
  'Actions': 'Действия',
  'Catalog and access control': 'Каталог и управление доступом',
  'Access denied': 'Доступ запрещён',
  'Back to app': 'Вернуться',
  'Loading admin panel...': 'Загрузка панели администратора...',
  'Admin access required': 'Требуется доступ администратора',
  'You do not have permission to view this panel.': 'У вас нет прав для просмотра этой панели.',
  'Add comment': 'Добавить комментарий',
  'Timestamp': 'Время',
  'Use current time': 'Текущее время',
  'Leave a comment for this moment...': 'Оставьте комментарий к этому моменту...',
  'Close discover genre modal': 'Закрыть окно выбора жанра',
  'Recommendations': 'Рекомендации',
  'Pick a genre and open a dedicated page with 5 tracks similar to the music you already liked.': 'Выберите жанр, чтобы получить 5 треков, похожих на ваши любимые песни.',
  'Open recommendations': 'Открыть рекомендации',
  'Loading genres...': 'Загрузка жанров...',
  'No genres with tracks are available yet.': 'Жанров с доступными треками пока нет.',
  'Could not load genres': 'Не удалось загрузить жанры',
  'Select the file or drag it in': 'Выберите файл или перетащите его сюда',
  'Crop preview': 'Предпросмотр обрезки',
  'Save': 'Сохранить',
  'Choose another': 'Выбрать другой',
  'Selected image preview': 'Предпросмотр выбранного изображения',
  'Invalid file type. Allowed:': 'Недопустимый тип файла. Разрешено:',
  'File too large. Maximum size:': 'Файл слишком большой. Максимальный размер:',
  'Could not process image': 'Не удалось обработать изображение',
  'Upload file': 'Загрузить файл',
  'Select an option': 'Выберите вариант',
  'Add a track': 'Добавить трек',
  'From liked songs': 'Из любимых песен',
  'Filter tracks': 'Фильтр треков',
  'Add': 'Добавить',
  'Recommended tracks': 'Рекомендуемые треки',
  'Single': 'Сингл',
  'Admin panel': 'Панель администратора',
  'Become artist': 'Стать исполнителем',
  'Your artist page': 'Страница исполнителя',
  'Close messenger': 'Закрыть мессенджер',
  'Open messenger': 'Открыть мессенджер',
  'Switch to light mode': 'Переключить на светлую тему',
  'Switch to dark mode': 'Переключить на тёмную тему',
  'Logout': 'Выйти',
  'Loading profile...': 'Загрузка профиля...',
  'Placeholder song': 'Название песни',
  'Current Session': 'Текущая сессия',
  'Add to liked songs': 'Добавить в любимые песни',
  'Shuffle': 'Перемешать',
  'Previous': 'Предыдущая',
  'Pause': 'Пауза',
  'Play': 'Воспроизвести',
  'Next': 'Следующая',
  'Repeat': 'Повтор',
  'Repeat one': 'Повторять один трек',
  'Repeat all': 'Повторять всё',
  'Repeat off': 'Повтор выключен',
  'Queue': 'Очередь',
  'Volume': 'Громкость',
  'Mute': 'Выключить звук',
  'Unmute': 'Включить звук',
  'Open album': 'Открыть альбом',
  'Album is unavailable': 'Альбом недоступен',
  'Close sidebar': 'Закрыть боковую панель',
  'Liked Songs': 'Любимые песни',
  'Reset changes': 'Сбросить изменения',
  'Clear form': 'Очистить форму',
  'title': 'Название',
  'Album cover': 'Обложка альбома',
  'Replace album cover': 'Заменить обложку альбома',
  'Leave empty to keep the current cover': 'Оставьте пустым, чтобы сохранить текущую обложку',
  'Supported formats: JPEG, PNG. Maximum size: 10MB': 'Поддерживаемые форматы: JPEG, PNG. Максимальный размер: 10 МБ',
  'Add track': 'Добавить трек',
  'Track title': 'Название трека',
  'Track name': 'Название трека',
  'Select genre': 'Выберите жанр',
  'Audio file': 'Аудиофайл',
  'Save track': 'Сохранить трек',
  'Save changes': 'Сохранить изменения',
  'Title': 'Название',
  'Audio': 'Аудио',
  'Duration': 'Длительность',
  'Uploaded': 'Загружен',
  'Edit': 'Редактировать',
  'Remove': 'Удалить',
  'No tracks in this album yet.': 'Треков в этом альбоме пока нет.',
  'Create an album': 'Создать альбом',
  'Edit album': 'Редактировать альбом',
  'Create': 'Создать',
  'File error occurred': 'Произошла ошибка файла',
  'Could not read track duration. The track can still be uploaded.': 'Не удалось прочитать длительность трека. Трек всё равно можно загрузить.',
  'Fill track title and genre': 'Заполните название трека и жанр',
  'Upload an audio file': 'Загрузите аудиофайл',
  'Track edit state is invalid': 'Некорректное состояние редактирования трека',
  'Track not found': 'Трек не найден',
  'Failed to delete track': 'Не удалось удалить трек',
  'Failed to create album': 'Не удалось создать альбом',
  'Album id is missing': 'Не указан ID альбома',
  'Only the album owner can edit this album': 'Только владелец альбома может редактировать этот альбом',
  'Failed to load album data': 'Не удалось загрузить данные альбома',
  'Album editor': 'Редактор альбома',
  'New release': 'Новый релиз',
  'Update the album metadata, artwork and track list before saving.': 'Обновите данные альбома, обложку и список треков перед сохранением.',
  'Build the release cover and track list before creating the album.': 'Подготовьте обложку релиза и список треков перед созданием.',
  'Mode': 'Режим',
  'Artwork': 'Обложка',
  'Ready': 'Готово',
  'Missing': 'Отсутствует',
  'Track editor': 'Редактор трека',
  'Track state': 'Состояние треков',
  'Review title and cover': 'Проверьте название и обложку',
  'Replace or remove tracks if needed': 'При необходимости замените или удалите треки',
  'Save changes when the release looks right': 'Сохраните изменения, когда всё будет готово',
  'Add an album title': 'Добавьте название альбома',
  'Upload a square cover': 'Загрузите квадратную обложку',
  'Prepare at least one track before publishing': 'Подготовьте хотя бы один трек перед публикацией',
  'Track editor is open': 'Редактор трека открыт',
  'No pending new tracks': 'Нет ожидающих новых треков',
  '{count} pending track(s)': '{count} трек(ов) в ожидании',
  '{count} existing track(s)': '{count} существующих трек(ов)',
  '{count} new track(s) in queue': '{count} новых трек(ов) в очереди',
  'Existing track': 'Существующий трек',
  'Leave empty to keep current uploaded audio': 'Оставьте пустым, чтобы сохранить текущий загруженный аудиофайл',
  'Select audio file': 'Выберите аудиофайл',
  'Untitled': 'Без названия',
  'Pending': 'Ожидается',
  'Checklist': 'Чеклист',
  'Field': 'Поле',
  'Status': 'Статус',
  'Waiting': 'Ожидание',
  'Review the preview before saving': 'Проверьте превью перед сохранением',
  'Use the form and artwork preview to shape this page before publishing.': 'Используйте форму и превью обложки, чтобы подготовить страницу перед публикацией.',
  'This editor keeps the form focused on a single change.': 'Этот редактор держит форму сфокусированной на одном изменении.',
  'Loading messenger...': 'Загрузка мессенджера...',
  'Share with someone': 'Поделиться с кем-то',
  'Choose a conversation or a user to send this card.': 'Выберите диалог или пользователя, чтобы поделиться.',
  'Recent conversations': 'Недавние диалоги',
  'Open chat': 'Открыть чат',
  'New chat': 'Новый чат',
  'You are not following anyone yet': 'Вы пока ни на кого не подписаны',
  'You can still open any user page and start a conversation from there.': 'Вы всё равно можете открыть страницу любого пользователя и начать диалог оттуда.',
  'Loading conversation...': 'Загрузка диалога...',
  'No messages yet': 'Сообщений пока нет',
  'Say hello and start the conversation.': 'Поздоровайтесь и начните разговор.',
  'Ready to share': 'Готово к отправке',
  'Write a message...': 'Напишите сообщение...',
  'Sending...': 'Отправка...',
  'Send': 'Отправить',
  'Messenger': 'Мессенджер',
  'Direct messages': 'Личные сообщения',
  'Chats and following': 'Чаты и подписки',
  'Track': 'Трек',
  'Share': 'Поделиться',
  'Tap to play': 'Нажмите, чтобы воспроизвести',
  'Open page': 'Открыть страницу',
  'Open public page': 'Открыть страницу',
  'Shared a': 'Поделился',
  'No comments yet': 'Комментариев пока нет',
  'Track comments': 'Комментарии к треку',
  'Close comments': 'Закрыть комментарии',
  'Loading comments...': 'Загрузка комментариев...',
  'No track selected': 'Трек не выбран',
  'Start playing a track to see and leave comments.': 'Начните воспроизведение трека, чтобы видеть и оставлять комментарии.',
  'Be the first to leave a note for this moment in the track.': 'Станьте первым, кто оставит заметку к этому моменту трека.',
  'Comment': 'Комментарий',
  'Edit comment': 'Редактировать комментарий',
  'Delete comment': 'Удалить комментарий',
  'Edit message': 'Редактировать сообщение',
  'Delete message': 'Удалить сообщение',
  'Log in': 'Войти',
  'Logging in...': 'Вход...',
  "Don't have an account?": 'Нет аккаунта?',
  'Sign up now': 'Зарегистрироваться',
  'Email': 'Email',
  'Password': 'Пароль',
  'Email is required': 'Email обязателен',
  'Invalid email format': 'Неверный формат email',
  'Password is required': 'Пароль обязателен',
  'Password must be at least {count} characters': 'Пароль должен содержать минимум {count} символов',
  'Fill in both password fields': 'Заполните оба поля пароля',
  'Sign up': 'Регистрация',
  'Signing up...': 'Регистрация...',
  'Already have an account?': 'Уже есть аккаунт?',
  'Username': 'Имя пользователя',
  'Username is required': 'Имя пользователя обязательно',
  'Username must be at least 2 characters': 'Имя пользователя должно содержать минимум 2 символа',
  'Error during login': 'Ошибка при входе',
  'Error during registration': 'Ошибка при регистрации',
  'Could not search right now': 'Сейчас не удалось выполнить поиск',
  'View all results for': 'Показать все результаты для',
  'Log out everywhere': 'Выйти на всех устройствах',
  'Log out of this session': 'Выйти из этой сессии',
  'Now': 'Сейчас',
  'Track stream is not available': 'Поток трека недоступен',
  'Could not resolve track stream': 'Не удалось получить поток трека',
  'Player is not ready': 'Плеер не готов',
  'Could not start playback': 'Не удалось начать воспроизведение',
  'Could not resume playback': 'Не удалось продолжить воспроизведение',
  'Could not load track comments': 'Не удалось загрузить комментарии к треку',
  'Track is not selected': 'Трек не выбран',
  'Comment cannot be empty': 'Комментарий не может быть пустым',
  'Could not send comment': 'Не удалось отправить комментарий',
  'Could not update comment': 'Не удалось обновить комментарий',
  'Could not delete comment': 'Не удалось удалить комментарий',
  'No data available': 'Нет данных',
  'Loading library...': 'Загрузка библиотеки...',
  'No playlists yet.': 'Плейлистов пока нет.',
  'Nothing saved yet': 'Пока ничего не сохранено',
  'Follow users, artists, albums or playlists to keep them here.': 'Подписывайтесь на пользователей, исполнителей, альбомы и плейлисты, чтобы они появлялись здесь.',
  'Could not remove user': 'Не удалось убрать пользователя',
  'Could not remove artist': 'Не удалось убрать исполнителя',
  'Could not remove album': 'Не удалось убрать альбом',
  'Could not remove playlist': 'Не удалось убрать плейлист',
  'Failed to load library': 'Не удалось загрузить библиотеку',
  'Loading playlist...': 'Загрузка плейлиста...',
  'Private': 'Приватный',
  'Delete': 'Удалить',
  'Share playlist': 'Поделиться плейлистом',
  'No tracks yet.': 'Треков пока нет.',
  'Could not load playlist': 'Не удалось загрузить плейлист',
  'Delete this playlist?': 'Удалить этот плейлист?',
  'Could not delete': 'Не удалось удалить',
  'Could not add': 'Не удалось добавить',
  'Could not update library': 'Не удалось обновить библиотеку',
  'Could not add track': 'Не удалось добавить трек',
  'No playlists available': 'Нет доступных плейлистов',
  'Login required': 'Требуется вход',
  'Add to playlist': 'Добавить в плейлист',
  'Remove from this playlist': 'Удалить из этого плейлиста',
  'Remove from your Liked Songs': 'Удалить из ваших любимых песен',
  'Save to your Liked Songs': 'Сохранить в ваши любимые песни',
  'Could not update liked songs': 'Не удалось обновить любимые песни',
  'Add to queue': 'Добавить в очередь',
  'Share to user': 'Поделиться с пользователем',
  'Go to artist': 'Перейти к исполнителю',
  'Go to album': 'Перейти к альбому',
  'Could not load liked songs': 'Не удалось загрузить любимые песни',
  'Listen': 'Слушать',
  'Loading albums...': 'Загрузка альбомов...',
  'Loading album...': 'Загрузка альбома...',
  'New album': 'Новый альбом',
  'Popular': 'Популярное',
  'Plays': 'Просл.',
  'Time': 'Время',
  'No albums yet': 'Альбомов пока нет',
  'This artist has not released albums yet.': 'Этот исполнитель пока не выпустил альбомов.',
  'Could not update artist follow state': 'Не удалось обновить подписку на исполнителя',
  'Failed to load albums': 'Не удалось загрузить альбомы',
  'Back to albums': 'Назад к альбомам',
  'Share artist': 'Поделиться исполнителем',
  'Share album': 'Поделиться альбомом',
  'Album title': 'Название альбома',
  'Failed to rename album': 'Не удалось переименовать альбом',
  'Could not start track streaming': 'Не удалось запустить воспроизведение трека',
  'Delete this album?': 'Удалить этот альбом?',
  'Failed to delete album': 'Не удалось удалить альбом',
  'Failed to load album': 'Не удалось загрузить альбом',
  'Search': 'Поиск',
  'Search results': 'Результаты поиска',
  'Search results for "{query}"': 'Результаты поиска по запросу "{query}"',
  'Enter a query in the top search bar to find music.': 'Введите запрос в верхней строке поиска, чтобы найти музыку.',
  'No tracks, albums, playlists, artists, users or genres found for “{query}”.': 'По запросу “{query}” не найдено треков, альбомов, плейлистов, исполнителей, пользователей или жанров.',
  'Toggle liked song': 'Переключить любимый трек',
  'Play {title}': 'Воспроизвести {title}',
  'Could not update follow state': 'Не удалось обновить состояние подписки',
  'Could not load search results': 'Не удалось загрузить результаты поиска',
  'Loading home...': 'Загрузка главной страницы...',
  'No artists yet.': 'Исполнителей пока нет.',
  'Latest albums': 'Новые альбомы',
  "Users's playlists": 'Плейлисты пользователей',
  "User's playlists": 'Плейлисты пользователей',
  'Failed to load home page': 'Не удалось загрузить главную страницу',
  'Loading playlists...': 'Загрузка плейлистов...',
  '{count} playlists': '{count} playlists',
  'New playlist': 'Новый плейлист',
  'Create playlist': 'Создать плейлист',
  'No playlists yet': 'Плейлистов пока нет',
  'You have no playlists yet.': 'У вас пока нет плейлистов.',
  'Create one': 'Создать',
  'Could not load playlists': 'Не удалось загрузить плейлисты',
  'Edit playlist': 'Редактировать плейлист',
  'Save playlist': 'Сохранить плейлист',
  'Playlist name': 'Название плейлиста',
  'Cover (optional)': 'Обложка (необязательно)',
  'Playlist editor': 'Редактор плейлиста',
  'Update the playlist title and cover that listeners see in the library.': 'Обновите название и обложку плейлиста, которые пользователи видят в библиотеке.',
  'Playlist cover': 'Обложка плейлиста',
  'Rename the playlist clearly': 'Дайте плейлисту понятное название',
  'Choose a square cover image': 'Выберите квадратную обложку',
  'Save changes to update the library view': 'Сохраните изменения, чтобы обновить вид библиотеки',
  'Shape the playlist title and cover before it goes into the library.': 'Подготовьте название и обложку плейлиста перед тем, как он появится в библиотеке.',
  'Decide whether the playlist is public or private': 'Решите, будет плейлист публичным или приватным',
  'Cover upload failed': 'Не удалось загрузить обложку',
  'Enter a name for the playlist': 'Введите название плейлиста',
  'Failed to create playlist': 'Не удалось создать плейлист',
  'Failed to update playlist': 'Не удалось обновить плейлист',
  'Your public library': 'Ваша публичная библиотека',
  'User library': 'Библиотека пользователя',
  'Open artist page': 'Открыть страницу артиста',
  'Opening...': 'Открытие...',
  'Message': 'Сообщение',
  'Library overview': 'Обзор библиотеки',
  'Nothing public yet': 'Пока ничего публичного нет',
  'This library does not have followed users, artists, albums or playlists yet.': 'В этой библиотеке пока нет пользователей, исполнителей, альбомов или плейлистов в подписках.',
  'Saved playlists': 'Сохранённые плейлисты',
  'Failed to load user library': 'Не удалось загрузить библиотеку пользователя',
  'Edit profile': 'Редактировать профиль',
  'Save profile': 'Сохранить профиль',
  'Current avatar': 'Текущий аватар',
  'User avatar': 'Аватар пользователя',
  'Account avatar': 'Аватар аккаунта',
  'Display name': 'Отображаемое имя',
  'Artist nickname': 'Псевдоним исполнителя',
  'Country': 'Страна',
  'Select your country': 'Выберите страну',
  'Current artist image': 'Текущее изображение исполнителя',
  'Artist image': 'Изображение исполнителя',
  'Change password': 'Сменить пароль',
  'Reset': 'Сбросить',
  'Could not load profile': 'Не удалось загрузить профиль',
  'Avatar upload failed': 'Не удалось загрузить аватар',
  'Artist image upload failed': 'Не удалось загрузить изображение исполнителя',
  'Could not update artist profile': 'Не удалось обновить профиль исполнителя',
  'Profile updated successfully': 'Профиль успешно обновлён',
  'Could not save profile': 'Не удалось сохранить профиль',
  'Profile': 'Профиль',
  'Update account details, avatar and public artist profile in one place.': 'Обновите данные аккаунта, аватар и публичный профиль артиста в одном месте.',
  'Update the account data and avatar used across the app.': 'Обновите данные аккаунта и аватар, используемые в приложении.',
  'Role': 'Роль',
  'Not set': 'Не указано',
  'Update display name and avatar': 'Обновите отображаемое имя и аватар',
  'Review artist nickname and country': 'Проверьте псевдоним артиста и страну',
  'Adjust the artist image if needed': 'При необходимости обновите изображение артиста',
  'Update display name': 'Обновите отображаемое имя',
  'Review email and avatar': 'Проверьте email и аватар',
  'Use change password for credentials': 'Используйте смену пароля для учётных данных',
  'Countries': 'Страны',
  'Songs': 'Треки',
  'Comments': 'Комментарии',
  'Search {entity}': 'Поиск: {entity}',
  'Search, inspect and edit {entity} records.': 'Ищите, просматривайте и редактируйте записи сущности «{entity}».',
  'Loading {entity}...': 'Загрузка: {entity}...',
  'Unsupported entity': 'Неподдерживаемая сущность',
  'Could not load admin records': 'Не удалось загрузить записи панели администратора',
  'No records found': 'Записи не найдены',
  'Try another search query.': 'Попробуйте другой поисковый запрос.',
  'Page {current} of {total}': 'Страница {current} из {total}',
  'Delete "{label}" from the database?': 'Удалить «{label}» из базы данных?',
  'Could not delete record': 'Не удалось удалить запись',
  'Edit record fields available to the admin panel.': 'Отредактируйте поля записи, доступные в панели администратора.',
  'Loading record...': 'Загрузка записи...',
  'Enabled': 'Включено',
  'Deleting...': 'Удаление...',
  'Delete record': 'Удалить запись',
  'Record': 'Запись',
  'Changes saved': 'Изменения сохранены',
  'Could not load record': 'Не удалось загрузить запись',
  'Could not save record': 'Не удалось сохранить запись',
  'Back to {entity}': 'Назад к разделу «{entity}»',
  'Back to users': 'Назад к пользователям',
  'Back to genres': 'Назад к жанрам',
  'Back to countries': 'Назад к странам',
  'Create user': 'Создать пользователя',
  'Create country': 'Создать страну',
  'Create genre': 'Создать жанр',
  'Create a new account and choose its platform role.': 'Создайте новую учётную запись и выберите её роль на платформе.',
  'Add a reusable genre for albums and songs.': 'Добавьте переиспользуемый жанр для альбомов и треков.',
  'Add a country entry for artist metadata.': 'Добавьте страну для метаданных исполнителей.',
  'Name': 'Имя',
  'Id': 'ID',
  'Created At': 'Создано',
  'Updated At': 'Обновлено',
  'Confirm password': 'Подтвердите пароль',
  'Minimum 8 characters': 'Минимум 8 символов',
  'Repeat password': 'Повторите пароль',
  'User role': 'Роль пользователя',
  'Password must be at least 8 characters': 'Пароль должен содержать минимум 8 символов',
  'Password confirmation does not match': 'Подтверждение пароля не совпадает',
  'Could not create user': 'Не удалось создать пользователя',
  'Genre name': 'Название жанра',
  'Could not create genre': 'Не удалось создать жанр',
  'Country name': 'Название страны',
  'Could not create country': 'Не удалось создать страну',
  'Upload track': 'Загрузить трек',
  'Back to songs': 'Назад к трекам',
  'First we read the file metadata and build a Spotify-based draft. Nothing is saved to the database until you confirm creation.': 'Сначала мы читаем метаданные файла и собираем черновик на основе Spotify. В базу данных ничего не сохраняется, пока вы не подтвердите создание.',
  'Analyzing...': 'Анализ...',
  'Analyze track': 'Анализировать трек',
  'Duplicate track found': 'Найден дубликат трека',
  'This track': 'Этот трек',
  'already exists': 'уже существует',
  'by': 'исполнителя',
  'on': 'в альбоме',
  'You can still re-upload it to refresh the audio file and save the Spotify metadata into the existing record.': 'Вы всё ещё можете загрузить его повторно, чтобы обновить аудиофайл и сохранить метаданные Spotify в существующей записи.',
  'Open existing record': 'Открыть существующую запись',
  'Import warnings': 'Предупреждения импорта',
  'Review draft': 'Проверка черновика',
  'Release date': 'Дата релиза',
  'Tempo': 'Темп',
  'Energy': 'Энергия',
  'Danceability': 'Танцевальность',
  'Valence': 'Позитивность',
  'Play count': 'Количество прослушиваний',
  'Popularity (derived)': 'Популярность (расчётная)',
  'Spotify track ID': 'ID трека Spotify',
  'Spotify': 'Spotify',
  'Matched': 'Совпадение найдено',
  'No match': 'Совпадений нет',
  'Audio features': 'Аудио-характеристики',
  'Loaded': 'Загружены',
  'Manual input required': 'Нужно заполнить вручную',
  'Popularity': 'Популярность',
  'Optional recommendation fields left blank:': 'Необязательные рекомендательные поля оставлены пустыми:',
  'Create track': 'Создать трек',
  'Re-upload existing track': 'Повторно загрузить существующий трек',
  'Track created': 'Трек создан',
  'was re-uploaded and updated in the catalog.': 'был повторно загружен и обновлён в каталоге.',
  'was added to the catalog.': 'был добавлен в каталог.',
  'Edit song record': 'Редактировать запись трека',
  'Could not read track duration from the file in browser metadata.': 'Не удалось прочитать длительность трека из метаданных файла в браузере.',
  'Matched in Spotify and loaded recommendation fields. Review the draft and confirm creation.': 'Совпадение найдено в Spotify, рекомендательные поля загружены. Проверьте черновик и подтвердите создание.',
  'Matched in Spotify. Review the draft and fill any missing recommendation fields before saving.': 'Совпадение найдено в Spotify. Проверьте черновик и при необходимости заполните недостающие рекомендательные поля перед сохранением.',
  'Draft created from file metadata. Review the fields before saving.': 'Черновик создан из метаданных файла. Проверьте поля перед сохранением.',
  'Re-uploading track': 'Повторная загрузка трека',
  'Creating track': 'Создание трека',
  'Processing track': 'Обработка трека',
  'Updating the existing catalog record and replacing the audio file. Keep this page open.': 'Обновляем существующую запись каталога и заменяем аудиофайл. Не закрывайте эту страницу.',
  'Creating the track and saving the uploaded audio file. Keep this page open.': 'Создаём трек и сохраняем загруженный аудиофайл. Не закрывайте эту страницу.',
  'Reading the audio file metadata and looking for Spotify matches.': 'Читаем метаданные аудиофайла и ищем совпадения в Spotify.',
  'Could not analyze track': 'Не удалось проанализировать трек',
  'Could not create track': 'Не удалось создать трек',
}

const interpolate = (text: string, params?: Record<string, string | number>) => {
  if (!params) {
    return text
  }

  return Object.entries(params).reduce((result, [key, value]) => {
    return result.replaceAll(`{${key}}`, String(value))
  }, text)
}

export const useLocalizedText = () => {
  const { locale } = useI18n()

  const tl = (text: string, params?: Record<string, string | number>) => {
    if (!text) {
      return ''
    }

    const source = locale.value === 'ru'
      ? (russianLiterals[text] || text)
      : text

    return interpolate(source, params)
  }

  return {
    tl,
  }
}
